baseURL = "https://wfan19.github.io"
theme = "vitmat"
title="Hi, I'm Bill!"
author="Bill Fan"

[params]
favicon="favicon.ico"

## Intro section / header configuration
[params.intro]
header = "Hi! I'm Bill."
img_faceshot = "images/Bill_headshot_2024.png"
email = "billfan.2001@gmail.com"

# Intro section paragraphs - each paragraph is a list entry
[[params.intro.paragraph]]
text="Hi! I'm a robotics engineer and researcher who just graduated from Olin College of Engineering."

[[params.intro.paragraph]]
text="""As a researcher, I've derived novel models and algorithms based on biomechanics in snakes, octopuses, and elephants, \
and I've used these to design and control soft robot arms to safely work alongside humans. \
I published this work as the first author in my 3rd year, and was invited to give a conference talk as the sole undergrad speaker, where it won 3rd best poster at a workshop."""

[[params.intro.paragraph]]
text="""As an engineer, I've developed robotics controls and sensing algorithms on hydrofioiling boats and construction robots. \
This includes firmware, nonlinear controllers, SLAM algorithms, simulators, and motion capture, both in C++ and Python."""

[[params.intro.paragraph]]
text="""I am currently building novel genome sequencing technologies at XGenomes as a microfluidics engineer while applying to PhD programs this fall. \
I'm interested in applying computational modeling to better understand biological systems, and using this understanding to improve engineered solutions."""

## Research section configuration
[params.research_section]
show = true
header = "Publications."

# Each research experience is its own entry
[[params.research_section.entry]]
image = "images/robosoft_25_thumbnail.png"
title = """A Fast and Model Based Approach for Evaluating Task-Competence of Antagonistic Continuum Arms"""
authors = "Bill Fan, Jacob Roulier, Gina Olson"
blurb = """Determining whether a proposed continuum arm design can complete a specified task and load is \
computationally expensive due to the need for simulation. We introduce a novel method of analysis that eliminates \
the need for simulation, speeding up computation by 80x, and creates novel metrics for evaluating arm designs against tasks. *Olin, UMass* | *Under review for Robosoft 2025*. 
"""
paper="pdfs/Robosoft_2025_11_8.pdf"

[[params.research_section.entry]]
image = "images/ASEE 200x300.jpg"
title = """Beyond "How's it going?": A Collaborative Autoethnographic Study by Early Instructors in a First-Year Engineering Studio Course"""
authors = "Esme E Abbot, Berwin Lan, Luke Raus, **Bill Fan**, Zachary del Rosario"
blurb = """
Studio teaching is increasingly popular, but teaching in one is difficult, especially for new instructors. \
We studied how new instructors learn to teach in a studio environment through a collective ethnography of \
four undergrad course assistants. We identified challenges new instructors faced and strategies they in response. *Olin* | *ASEE 2024*."""

paper = "pdfs/ASEE_2024_ModSim_CAE.pdf"

[[params.research_section.entry]]
image = "images/snake_boomerang_700x1082.gif"
title = "Linear Kinematics for General Constant Curvature and Torsion Manipulators"
authors = "**Bill Fan***, Farhan Rozaidi, Capprin Bass, Gina Olson, Melinda Malley, Ross L Hatton"
blurb = """
Inspired by octopus arms, helically-wound muscles greatly increase continuum arm workspaces, but they are more difficult to model and control. \ 
We present a novel application of Lie theory to simplify the modeling of constant twist soft robots, and unify modeling across different designs. \
Lightning talk at Robosoft 2023, and 3rd place best workshop poster. *Olin, OSU, UMass* | *Robosoft 2023*"""
paper = "https://arxiv.org/abs/2302.11661"
poster = "pdfs/Robosoft_Poster.pdf"

# [[params.research_section.entry]]
# image="images/underwater slam.png"
# title = "Simultaneous Localization and Mapping for a Robotic Fish"
# authors = "**Bill Fan**, Declan Freeman-Gleason, David Barrett"
# blurb = """
# Experimented with using an Unscented Kalman Filter and Apriltags to perform SLAM for a robotic fish. \
# Compared different algorithm choices and manifold representations. \
# Designed experiment setup and collected datasets for validating the UKF. \
# Submitted an abstract to IEEE OCEANS 2021. [[abstract]](pdfs/IEEE_Oceans_SD_Abstract.pdf)"""


## Projects section configuration
[params.projects_section]
show = true
header = "Projects."

# Each project card is its own entry
# unfinished: Links from the project card to detailed pages
[[params.projects_section.entry]]
image = "images/twist lab group.JPG"
title="Co-founding a soft-robotics research group"
img_posn = "50% 40%"
blurb = """In my 3rd year I co-founded Twist Lab - a soft robotics research group with 10 students. \
As PM I was responsible for raising over $7,500 in lab funding from grants, supported projects in the \
design, control, and simulation of soft robotics, and helped students apply to fellowships. """
url="/projects/twist_lab"

[[params.projects_section.entry]]
image = "images/foiling.gif"
title="Autonomous foiling of a Nacra 17"
blurb="""During my gap year before college, I built an autonomously hydrofoiling boat prototype at an early stage startup capable \
of multiple minutes of airtime. We added motorized hydrofoils with \
ROS controls to an existing boat hull, developed a simulation, and used it to implement a cascaded PID controller. """
img_posn = "70% 20%"
url="/projects/hydrofoiling"

[[params.projects_section.entry]]
image= "images/maglev_cropped.gif"
title= "Design and control of a maglev system."
blurb= """As the lead course assistant, I (re-)designed the final-project system for the Feedback Controls course at Olin, and created kits for all students. \
In the month-long project the students levitate a permanent magnet using an electromagnet and a hall-effect sensor. Gif by Krishna Suresh.
"""
url="/projects/maglev"

[[params.projects_section.entry]]
image = "images/500_balls_300x300.gif"
title="GPU Rendered Colloidal Glass Simulation"
blurb = """In my scientific computing class, I implemented a particle based model of the non-linear phase change of glass using Python. \
To render the results, I implemented a modern OpenGL GPU-programming shader pipeline, complete with a phong lighting model and full camera movement in 3D space. """
url="/projects/unfinished"

## Projects page
[params.projects_page]
[[params.projects_page.entry]]
image="images/twist lab group.JPG"
title="Twist Lab: co-founding a student-run soft robotics research group."
width=2
img_posn="50% 40%"
url="/projects/twist_lab"

[[params.projects_page.entry]]
image="images/foiling.gif"
title="Autonomous control of a hydrofoiling Nacra 17 watercraft."
width=2
url="/projects/hydrofoiling"

[[params.projects_page.entry]]
image="images/gcs_success.png"
title="Path planning w/ mixed-integer optimization."
url="/projects/gcs"

[[params.projects_page.entry]]
image="images/500_balls_300x300.gif"
title="Simulating and rendering mass particle collisions."
url="/projects/unfinished"

[[params.projects_page.entry]]
image="images/maglev_cropped.gif"
title="Design and control of a maglev system."
url="/projects/maglev"

[[params.projects_page.entry]]
image="images/awesome_ferrofluid.gif"
title="A ferrofluid display controlled by electromagnets."
url="https://pietroglyph.github.io/ferrofluid-display/"
img_posn="50% 80%"

[[params.projects_page.entry]]
image="images/bouncing_ball_fast.gif"
title="Simulation and optimal control of a bouncing ball by a movable platform"
img_posn="0%"
url="/projects/ball_bouncing"

[[params.projects_page.entry]]
image="images/neato star.jpg"
title="Art2D2: robotic drawing using lidar SLAM."
url="https://sites.google.com/view/comprobo-23-art2d2/home"
